### PR TITLE
Add "resizeMode" param on underlying Image component.

### PR DESCRIPTION
**Pull request by dbContext**
Please provide enough information so that others can review your pull request:

## Motivation
It removed the native functionality of resizeMode on the Image component, and this was needed for a feature I was implementing.

### CODE REVIEW

**Comment by likashefqet** [comment]
you should be able to override the resizeMode without these changes

**Comment by dbContext** [comment]
You can't, which is why I've made them.. unless you can show me otherwise?

**Comment by kimjson** [comment]
> You can't, which is why I've made them.. unless you can show me otherwise?

@dbContext  You can use styles.resizeMode like

```
<ImageZoom styles={{resizeMode: 'contain'}} {...otherProps} />
```

**Comment by likashefqet** [comment]
> You can't, which is why I've made them.. unless you can show me otherwise?

@dbContext Please check the example app

here are some examples:

cover code
cover demo

repeat code
repeat demo

stretch code
stretch demo

**Pull request closed without merging**
